import Batteries.CodeAction
import Batteries.Tactic.SeqFocus

/-! # Generic prelude

A small grab-bag of `List`, `Option` and reflexive-transitive-closure
lemmas used throughout the project. Anything that ought to live in
mathlib/batteries but isn't quite there ends up here. The only
domain-specific definition is `ReflTransGen`, which Term.lean's
multi-step weak-head reduction (`WHRedS`) is built on. -/

open Std

attribute [simp] Option.bind_eq_some_iff List.filterMap_cons

protected theorem List.Forall₂.rfl
    {R : α → α → Prop} {l : List α} (h : ∀ a ∈ l, R a a) : l.Forall₂ R l := by
  induction l with
  | nil => constructor
  | cons _ _ ih => simp at h; exact .cons h.1 (ih h.2)

@[simp] theorem List.forall₂_nil_left_iff {l} : Forall₂ R nil l ↔ l = nil :=
  ⟨fun H => by cases H; rfl, by rintro rfl; exact Forall₂.nil⟩

@[simp] theorem List.forall₂_nil_right_iff {l} : Forall₂ R l nil ↔ l = nil :=
  ⟨fun H => by cases H; rfl, by rintro rfl; exact Forall₂.nil⟩

theorem List.forall₂_cons_left_iff {a l u} :
    Forall₂ R (a :: l) u ↔ ∃ b u', R a b ∧ Forall₂ R l u' ∧ u = b :: u' :=
  Iff.intro
    (fun h => match u, h with | b :: u', Forall₂.cons h₁ h₂ => ⟨b, u', h₁, h₂, rfl⟩)
    (fun h => match u, h with | _, ⟨_, _, h₁, h₂, rfl⟩ => Forall₂.cons h₁ h₂)

theorem List.forall₂_cons_right_iff {b l u} :
    Forall₂ R u (b :: l) ↔ ∃ a u', R a b ∧ Forall₂ R u' l ∧ u = a :: u' :=
  Iff.intro
    (fun h => match u, h with | b :: u', Forall₂.cons h₁ h₂ => ⟨b, u', h₁, h₂, rfl⟩)
    (fun h => match u, h with | _, ⟨_, _, h₁, h₂, rfl⟩ => Forall₂.cons h₁ h₂)

@[simp] theorem List.forall₂_map_right_iff {f : γ → β} :
    ∀ {l u}, Forall₂ R l (map f u) ↔ Forall₂ (fun a c => R a (f c)) l u
  | _, [] => by simp only [map, forall₂_nil_right_iff]
  | _, b :: u => by simp only [map, forall₂_cons_right_iff, forall₂_map_right_iff]

theorem List.forall₂_eq {l₁ l₂ : List α} : Forall₂ Eq l₁ l₂ ↔ l₁ = l₂ :=
  ⟨fun h => by induction h <;> simp_all, (· ▸ .rfl fun _ _ => rfl)⟩

theorem List.perm_cons_of_mem {l : List α} (h : a ∈ l) : ∃ l', l.Perm (a :: l') := by
  obtain ⟨l₁, l₂, rfl⟩ := List.append_of_mem h; exact ⟨_, List.perm_middle⟩

theorem List.mapM_eq_some {f : α → Option β} {l : List α} {l' : List β} :
    l.mapM f = some l' ↔ List.Forall₂ (f · = some ·) l l' := by
  induction l generalizing l' with
  | nil => simp only [mapM_nil, pure, Option.some.injEq, forall₂_nil_left_iff, @eq_comm _ l']
  | cons x l ih =>
    simp [mapM_cons, Bind.bind, pure, Option.bind_eq_some_iff, Option.some.injEq,
      forall₂_cons_left_iff, @eq_comm _ l', exists_and_left, ih]

/-- Reflexive-transitive closure of a binary relation `R`, generated by adding
single steps on the right (`tail`). Used in `Term.lean` as the foundation for
multi-step weak-head reduction (`WHRedS = ReflTransGen WHRed`). -/
inductive ReflTransGen (R : α → α → Prop) (a : α) : α → Prop where
  | rfl : ReflTransGen R a a
  | tail : ReflTransGen R a b → R b c → ReflTransGen R a c

theorem ReflTransGen.trans
    (H1 : ReflTransGen R a b) (H2 : ReflTransGen R b c) : ReflTransGen R a c := by
  induction H2 with
  | rfl => exact H1
  | tail h1 h2 ih => exact ih.tail h2

@[elab_as_elim] theorem ReflTransGen.headIndOn {P : (a : α) → ReflTransGen R a z → Prop}
    (rfl : P z .rfl)
    (head : ∀ {x y} (h1 : R x y) (h2 : ReflTransGen R y z),
      P y h2 → P x (.trans (.tail .rfl h1) h2))
    (H : ReflTransGen R a z) : P a H := by
  induction H with
  | rfl => exact rfl
  | tail h1 h2 ih => exact ih (head h2 .rfl rfl) fun a1 a2 => head a1 (.tail a2 h2)
